-- MySQL Script generated by MySQL Workbench
-- 06/30/14 23:50:42
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ptransporteucv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ptransporteucv` DEFAULT CHARACTER SET utf8 ;
USE `ptransporteucv` ;

-- -----------------------------------------------------
-- Table `ptransporteucv`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ptransporteucv`.`usuario` (
  `id` VARCHAR(15) NOT NULL COMMENT 'El id del usuario',
  `password` VARCHAR(41) NOT NULL COMMENT 'La clave encriptada',
  `permisos` VARCHAR(20) NOT NULL COMMENT 'El id de los permisos correspondientes',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ptransporteucv`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ptransporteucv`.`actividad` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL COMMENT 'El usuario actor',
  `tiempo` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'El momento del evento',
  `actividad` VARCHAR(150) NULL COMMENT 'Descripcion del evento',
  PRIMARY KEY (`id`),
  INDEX `fk_actividad_usuario_idx` (`usuario` ASC),
  CONSTRAINT `fk_actividad_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `ptransporteucv`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 88
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ptransporteucv`.`ruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ptransporteucv`.`ruta` (
  `origen` VARCHAR(45) NOT NULL COMMENT 'El origen de la ruta',
  `destino` VARCHAR(45) NOT NULL COMMENT 'El final de la ruta',
  `id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ptransporteucv`.`parada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ptransporteucv`.`parada` (
  `id` INT(10) UNSIGNED NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NULL COMMENT 'Descripción de la parada: puntos de referencia del lugar, otros nombres, etc.',
  `ruta_id` INT(10) UNSIGNED NOT NULL COMMENT 'Ruta a la que pertenece',
  PRIMARY KEY (`id`),
  INDEX `fk_parada_ruta_idx` (`ruta_id` ASC),
  CONSTRAINT `fk_parada_ruta`
    FOREIGN KEY (`ruta_id`)
    REFERENCES `ptransporteucv`.`ruta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ptransporteucv`.`pasajero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ptransporteucv`.`pasajero` (
  `cedula` INT(8) UNSIGNED NOT NULL COMMENT 'La cedula de los pasajeros',
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ptransporteucv`.`transportista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ptransporteucv`.`transportista` (
  `primer_nombre` VARCHAR(45) NOT NULL,
  `segundo_nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT 'El segundo nombre es opcional.',
  `primer_apellido` VARCHAR(45) NOT NULL,
  `segundo_apellido` VARCHAR(45) NOT NULL,
  `fecha_nac` DATE NULL DEFAULT NULL,
  `cedula` INT(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`cedula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ptransporteucv`.`viaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ptransporteucv`.`viaje` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL COMMENT 'La fecha del viaje',
  `hora_salida` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Hora de partida',
  `hora_llegada` TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Hora de llegada',
  `ruta_id` INT(10) UNSIGNED NOT NULL COMMENT 'La ruta del viaje',
  `ci_transportista` INT(8) UNSIGNED NOT NULL COMMENT 'La cedula del chofer',
  PRIMARY KEY (`id`),
  INDEX `fk_viaje_transportista` (`ci_transportista` ASC),
  INDEX `fk_viaje_ruta` (`ruta_id` ASC),
  CONSTRAINT `fk_viaje_transportista`
    FOREIGN KEY (`ci_transportista`)
    REFERENCES `ptransporteucv`.`transportista` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viaje_ruta`
    FOREIGN KEY (`ruta_id`)
    REFERENCES `ptransporteucv`.`ruta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ptransporteucv`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ptransporteucv`.`registro` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `viaje_id` BIGINT(20) UNSIGNED NOT NULL COMMENT 'El viaje asociado al registro',
  `pasajero_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_registro_viaje_idx` (`viaje_id` ASC),
  INDEX `fk_registro_pasajero_idx` (`pasajero_id` ASC),
  CONSTRAINT `fk_registro_viaje`
    FOREIGN KEY (`viaje_id`)
    REFERENCES `ptransporteucv`.`viaje` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registro_pasajero`
    FOREIGN KEY (`pasajero_id`)
    REFERENCES `ptransporteucv`.`pasajero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
